### ISSUE TITLE
Separate test & lint and container build workflows for actions so that they can be triggered separately

### ISSUE THREAD

**Issue by rascasoft** [mmul-it/kpa#14]
Creating two workflow yml files instead of one, we can have kpa_generator trigger *just* the container build, since there's no big deal in having the lint and test repeated with no code changes and everything should become faster.

**Comment by rascasoft** [comment]
Have a look at this https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed specifically on the section:

2. Separate workflow, using [the workflow_run event as a trigger](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run)

Creating a yaml with:

```yaml
# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed
```

So with both  `workflow_dispatch:` and `workflow_run:` should do the trick.
